import { calculateRecoveryScore } from "@/lib/recovery-score";
import type { GarminDailyMetrics, MetricPoint, WorkoutDay } from "@/types/forma";

export const today = {
  weight: 176.4,
  calories: 1830,
  calorieGoal: 2350,
  protein: 142,
  proteinGoal: 175,
  water: 2.4,
  waterGoal: 3.2,
  steps: 8430,
  stepsGoal: 10000,
  sleep: 7.2,
  sleepGoal: 8,
  habitsDone: 5,
  habitsTotal: 7,
  workoutStatus: "Upper Strength at 6:00 PM",
};

export const progress = {
  weightChange: -1.8,
  consistency: 86,
  calorieTrend: "Stable deficit",
  workoutCompletion: 92,
};

export const metricSeries: MetricPoint[] = [
  { date: "Mon", weight: 178.2, calories: 2290, protein: 161, sleep: 7.1, volume: 14400 },
  { date: "Tue", weight: 177.8, calories: 2360, protein: 174, sleep: 6.7, volume: 0 },
  { date: "Wed", weight: 177.3, calories: 2210, protein: 168, sleep: 7.8, volume: 16800 },
  { date: "Thu", weight: 177.0, calories: 2325, protein: 179, sleep: 7.0, volume: 0 },
  { date: "Fri", weight: 176.6, calories: 2180, protein: 183, sleep: 8.1, volume: 15300 },
  { date: "Sat", weight: 176.5, calories: 2440, protein: 171, sleep: 7.5, volume: 9800 },
  { date: "Sun", weight: 176.4, calories: 1830, protein: 142, sleep: 7.2, volume: 0 },
];

export const workoutPlan: WorkoutDay[] = [
  {
    name: "Push",
    focus: "Chest, shoulders, triceps",
    exercises: [
      { name: "Bench Press", sets: 4, reps: "6-8", weight: "185 lb", rest: "2:30", tempo: "3-1-1" },
      { name: "Incline Dumbbell Press", sets: 3, reps: "8-10", weight: "70 lb", rest: "2:00" },
      { name: "Cable Fly", sets: 3, reps: "12-15", rest: "1:15" },
    ],
  },
  {
    name: "Pull",
    focus: "Back, rear delts, biceps",
    exercises: [
      { name: "Weighted Pull-up", sets: 4, reps: "5-7", weight: "+35 lb", rest: "2:30" },
      { name: "Barbell Row", sets: 4, reps: "8", weight: "165 lb", rest: "2:00" },
      { name: "Incline Curl", sets: 3, reps: "10-12", rest: "1:15" },
    ],
  },
  {
    name: "Legs",
    focus: "Quads, hamstrings, calves",
    exercises: [
      { name: "Back Squat", sets: 4, reps: "5", weight: "245 lb", rest: "3:00" },
      { name: "Romanian Deadlift", sets: 3, reps: "8", weight: "225 lb", rest: "2:30" },
      { name: "Seated Calf Raise", sets: 4, reps: "12-15", rest: "1:00" },
    ],
  },
];

export const exerciseDatabase = [
  {
    name: "Bench Press",
    muscle: "Chest",
    equipment: "Barbell",
    category: "Compound",
    instructions: "Retract shoulder blades, touch lower chest, press to stacked wrists.",
  },
  {
    name: "Back Squat",
    muscle: "Legs",
    equipment: "Barbell",
    category: "Compound",
    instructions: "Brace, sit between hips, keep midfoot pressure, drive up evenly.",
  },
  {
    name: "Lat Pulldown",
    muscle: "Back",
    equipment: "Cable",
    category: "Accessory",
    instructions: "Pull elbows toward ribs without leaning back excessively.",
  },
  {
    name: "Romanian Deadlift",
    muscle: "Hamstrings",
    equipment: "Barbell",
    category: "Hinge",
    instructions: "Soft knees, hinge hips back, keep lats tight and spine neutral.",
  },
];

export const garminMetrics: GarminDailyMetrics[] = [
  {
    date: "Mon",
    restingHeartRate: 54,
    hrv: 61,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 7.1,
    sleepScore: 78,
    deepSleepMinutes: 82,
    remSleepMinutes: 96,
    stressScore: 38,
    bodyBattery: 71,
    trainingReadiness: 74,
    trainingStatus: "Productive",
    recoveryTimeHours: 16,
    vo2Max: 49,
    steps: 9200,
    caloriesBurned: 2820,
    workoutIntensity: 42,
    intensityMinutes: 48,
  },
  {
    date: "Tue",
    restingHeartRate: 57,
    hrv: 54,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 6.5,
    sleepScore: 68,
    deepSleepMinutes: 64,
    remSleepMinutes: 88,
    stressScore: 56,
    bodyBattery: 52,
    trainingReadiness: 58,
    trainingStatus: "Maintaining",
    recoveryTimeHours: 24,
    vo2Max: 49,
    steps: 7800,
    caloriesBurned: 2480,
    workoutIntensity: 18,
    intensityMinutes: 20,
  },
  {
    date: "Wed",
    restingHeartRate: 53,
    hrv: 64,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 7.8,
    sleepScore: 84,
    deepSleepMinutes: 91,
    remSleepMinutes: 104,
    stressScore: 32,
    bodyBattery: 79,
    trainingReadiness: 81,
    trainingStatus: "Productive",
    recoveryTimeHours: 10,
    vo2Max: 50,
    steps: 10100,
    caloriesBurned: 3050,
    workoutIntensity: 68,
    intensityMinutes: 64,
  },
  {
    date: "Thu",
    restingHeartRate: 56,
    hrv: 57,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 7,
    sleepScore: 74,
    deepSleepMinutes: 76,
    remSleepMinutes: 92,
    stressScore: 47,
    bodyBattery: 63,
    trainingReadiness: 66,
    trainingStatus: "Maintaining",
    recoveryTimeHours: 22,
    vo2Max: 50,
    steps: 8700,
    caloriesBurned: 2630,
    workoutIntensity: 12,
    intensityMinutes: 18,
  },
  {
    date: "Fri",
    restingHeartRate: 52,
    hrv: 67,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 8.1,
    sleepScore: 88,
    deepSleepMinutes: 98,
    remSleepMinutes: 112,
    stressScore: 28,
    bodyBattery: 84,
    trainingReadiness: 86,
    trainingStatus: "Productive",
    recoveryTimeHours: 8,
    vo2Max: 50,
    steps: 11200,
    caloriesBurned: 3180,
    workoutIntensity: 74,
    intensityMinutes: 72,
  },
  {
    date: "Sat",
    restingHeartRate: 58,
    hrv: 51,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 6.8,
    sleepScore: 69,
    deepSleepMinutes: 58,
    remSleepMinutes: 84,
    stressScore: 61,
    bodyBattery: 46,
    trainingReadiness: 51,
    trainingStatus: "Strained",
    recoveryTimeHours: 34,
    vo2Max: 50,
    steps: 12400,
    caloriesBurned: 3320,
    workoutIntensity: 62,
    intensityMinutes: 58,
  },
  {
    date: "Sun",
    restingHeartRate: 54,
    hrv: 63,
    hrvBaseline: 58,
    restingHeartRateBaseline: 55,
    sleepDuration: 7.6,
    sleepScore: 86,
    deepSleepMinutes: 88,
    remSleepMinutes: 109,
    stressScore: 34,
    bodyBattery: 78,
    trainingReadiness: 80,
    trainingStatus: "Productive",
    recoveryTimeHours: 12,
    vo2Max: 50,
    steps: 8430,
    caloriesBurned: 2760,
    workoutIntensity: 24,
    intensityMinutes: 32,
  },
];

export const todaysGarminMetrics = garminMetrics[garminMetrics.length - 1];

export const recoveryToday = calculateRecoveryScore(todaysGarminMetrics);

export const recoveryTrend = garminMetrics.map((metrics) => ({
  ...metrics,
  recovery: calculateRecoveryScore(metrics).score,
}));
